name: Auto Review

on:
  pull_request:
    branches: [main]

jobs:
  ruff-review:
    name: ruff reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Sync dependencies
        run: uv sync --frozen
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: Ruff review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          uv run ruff check . --output-format=github | reviewdog -f=github -name="ruff" -reporter=github-pr-review -filter-mode=nofilter -fail-on-error=false
