name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  backend:
    name: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Sync dependencies
        run: uv sync --frozen
      - name: Prepare model artifact
        run: uv run python models/prepare_model.py
      - name: Ruff
        run: uv run ruff check .
      - name: Black
        run: uv run black --check .
      - name: Pytest
        env:
          PYTHONPATH: src
          MODEL_PATH: models/model.joblib
          API_USERNAME: admin
          API_PASSWORD: changeme
          JWT_SECRET: super-secret-key
          JWT_ALGORITHM: HS256
          JWT_EXPIRE_MINUTES: 30
          LOG_LEVEL: INFO
        run: uv run pytest
